sudo: false
language: ruby
rvm:
- 2.3.3

install:
- bundle install

script:
- bundle exec jekyll build

after_success:
- cd _site
- git config user.name "Travis CI"
- git config user.email "travis@travis-ci.org"
- git init
- git add .
- git commit -m "Travis build #${TRAVIS_BUILD_NUMBER}"
- git push --force "https://ryanaghdam:$GITHUB_API_KEY@github.com/ryanaghdam/ryanaghdam.github.io.git" HEAD:master &2>/dev/null
